######################################################################
# Automatically generated by qmake (2.01a) ? ??? 26 19:10:40 2009
######################################################################

TEMPLATE = app
VERSION = 0.2
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main_window.h
FORMS += main_window.ui
SOURCES += main.cpp main_window.cpp
